# Generated by Django 4.0.2 on 2022-06-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('invoice_number', models.IntegerField(null=True)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.BigIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
    ]
