# Generated by Django 4.0.2 on 2022-06-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_invoice_item_name_remove_invoice_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=2.2, max_digits=5),
            preserve_default=False,
        ),
    ]
